-- ============================================================
--  島嶼樂遊 / Island Sound  ── seed
--  資料來源：2026_台灣音樂祭資料庫.csv（已整合進此 SQL）
--  特性：所有 INSERT 皆為 idempotent（ON CONFLICT），可重複執行
--  說明：
--    1. regions 新增「基隆」（CSV 出現但原本缺漏），並重新編 sort_order（北→南）。
--    2. month 取自 date_start 的月份（schema 為單一整數；CSV「2-3月」取 2）。
--    3. blurb 一律 null（CSV 無描述欄位，未捏造）。
--    4. coord_x / coord_y 依城市估算（沿用原 seed 既有城市座標；
--       桃園 / 台東 / 基隆為新城市，依台灣地理位置估算）。
--    5. 演出陣容（lineup）全部匯入；以 CTE 為單一來源，
--       同時推導 artists 與 festival_artists，確保兩者名稱完全一致。
--       每場已去除場內重複藝人；火球祭先以「待公布」作為佔位藝人。
-- ============================================================

-- ─────────────────────────── regions ───────────────────────────
insert into public.regions (name_zh, name_en, sort_order) values
  ('基隆', 'Keelung',     1),
  ('台北', 'Taipei',      2),
  ('新北', 'New Taipei',  3),
  ('桃園', 'Taoyuan',     4),
  ('新竹', 'Hsinchu',     5),
  ('苗栗', 'Miaoli',      6),
  ('台中', 'Taichung',    7),
  ('彰化', 'Changhua',    8),
  ('南投', 'Nantou',      9),
  ('雲林', 'Yunlin',     10),
  ('嘉義', 'Chiayi',     11),
  ('台南', 'Tainan',     12),
  ('高雄', 'Kaohsiung',  13),
  ('屏東', 'Pingtung',   14),
  ('宜蘭', 'Yilan',      15),
  ('花蓮', 'Hualien',    16),
  ('台東', 'Taitung',    17)
on conflict (name_zh) do update
  set name_en    = excluded.name_en,
      sort_order = excluded.sort_order;


-- ─────────────────────────── festivals ───────────────────────────
insert into public.festivals
  (id, name, name_en, region_id, venue, date_start, date_end, month, blurb, coord_x, coord_y)
values
  ('lunghumen-247',
   '龍虎門 247 音樂日', 'Lung Hu Men 247 Music Day',
   (select id from public.regions where name_zh = '台北'),
   '台北流行音樂中心戶外表演空間', '2026-01-11', '2026-01-11', 1,
   null,
   0.760, 0.050),

  ('emerge',
   '浮現祭', 'Emerge Fest 2026',
   (select id from public.regions where name_zh = '台中'),
   '台中清水鰲峰山運動公園 (自由車場)', '2026-02-28', '2026-03-01', 2,
   null,
   0.290, 0.320),

  ('pp-festival',
   '北野祭', 'PP Festival 2026',
   (select id from public.regions where name_zh = '屏東'),
   '屏東高樹鄉新豐親水公園旁', '2026-03-06', '2026-03-08', 3,
   null,
   0.380, 1.000),

  ('yushan',
   '雨山祭', 'NCCU Music Festival',
   (select id from public.regions where name_zh = '台北'),
   '國立政治大學', '2026-03-07', '2026-03-07', 3,
   null,
   0.760, 0.050),

  ('kaka',
   '卡卡音樂祭', 'KAKA MUSIC FEST 2026',
   (select id from public.regions where name_zh = '桃園'),
   '國立中央大學戶外草坪', '2026-03-14', '2026-03-15', 3,
   null,
   0.580, 0.130),

  ('megaport',
   '大港開唱', 'Megaport Festival 2026',
   (select id from public.regions where name_zh = '高雄'),
   '高雄駁二藝術特區 / 愛河灣區', '2026-03-21', '2026-03-22', 3,
   null,
   0.100, 0.790),

  ('tmf',
   '台灣祭', 'Taiwan Music Festival 2026',
   (select id from public.regions where name_zh = '屏東'),
   '屏東墾丁大灣遊憩區（五大舞台）', '2026-04-03', '2026-04-05', 4,
   null,
   0.380, 1.000),

  ('pingtung-3days',
   '屏東三大日音樂節', 'Pingtung 3 Major Days Music Festival',
   (select id from public.regions where name_zh = '屏東'),
   '屏東縣立體育館前草地', '2026-04-10', '2026-04-12', 4,
   null,
   0.380, 1.000),

  ('nccu-summer',
   '政大夏日祭典', 'NCCU Summer Festival',
   (select id from public.regions where name_zh = '台北'),
   '國立政治大學四維道', '2026-04-28', '2026-04-30', 4,
   null,
   0.760, 0.050),

  ('siraya',
   '西拉雅森活節草原音樂祭', 'Siraya Forest Music Festival',
   (select id from public.regions where name_zh = '台南'),
   '西拉雅國家風景區', '2026-05-02', '2026-05-03', 5,
   null,
   0.010, 0.660),

  ('east-wave',
   '東浪嘉年華', 'East Wave Music Festival 2026',
   (select id from public.regions where name_zh = '台東'),
   '台東杉原灣', '2026-05-16', '2026-05-17', 5,
   null,
   0.620, 0.720),

  ('love-rock',
   '愛嶼搖滾', 'Love Rock Festival 2026',
   (select id from public.regions where name_zh = '基隆'),
   '基隆國門廣場、海洋廣場', '2026-05-23', '2026-05-24', 5,
   null,
   0.870, 0.010),

  ('hot-wave',
   '赤聲躁動音樂祭', 'Hot Wave Festival 2026',
   (select id from public.regions where name_zh = '台中'),
   '台中市豐原體育場', '2026-05-30', '2026-05-31', 5,
   null,
   0.290, 0.320),

  ('spring-wave',
   '春浪音樂節', 'Spring Wave Music Festival 2026 (20th)',
   (select id from public.regions where name_zh = '台中'),
   '台中外埔水渼渼露營區（6/26 前夜祭）', '2026-06-27', '2026-06-28', 6,
   null,
   0.290, 0.320),

  ('fireball',
   '火球祭', 'FireBall Fest. 2026',
   (select id from public.regions where name_zh = '桃園'),
   '樂天桃園棒球場', '2026-11-14', '2026-11-15', 11,
   null,
   0.580, 0.130)
on conflict (id) do update
  set name       = excluded.name,
      name_en    = excluded.name_en,
      region_id  = excluded.region_id,
      venue      = excluded.venue,
      date_start = excluded.date_start,
      date_end   = excluded.date_end,
      month      = excluded.month,
      blurb      = excluded.blurb,
      coord_x    = excluded.coord_x,
      coord_y    = excluded.coord_y;


-- ─────────────────────────── lineup（artists + festival_artists）───────────────────────────
-- 以 CTE 為單一資料來源，避免 SQL Editor 分段執行時找不到暫存/匯入表。

-- 推導 artists（去重）
with lineup (festival_id, artist_name, position) as (
  values
  -- 龍虎門 247 音樂日 (lunghumen-247)
  ('lunghumen-247', '滿人Manchuker', 0),
  ('lunghumen-247', 'J.Sheon', 1),
  ('lunghumen-247', '熊仔 Kumachan', 2),
  ('lunghumen-247', '健志 KEN-G', 3),
  ('lunghumen-247', '美麗本人', 4),
  ('lunghumen-247', '婁峻碩SHOU', 5),
  ('lunghumen-247', '呂士軒 Trout Fresh', 6),
  ('lunghumen-247', 'Barry Chen', 7),
  ('lunghumen-247', 'Gummy B', 8),
  ('lunghumen-247', 'M.V.M', 9),
  ('lunghumen-247', 'SHIGGA SHAY 西閣', 10),
  ('lunghumen-247', '潤少', 11),
  ('lunghumen-247', 'LilHAO', 12),
  ('lunghumen-247', '吳霏', 13),

  -- 浮現祭 (emerge)
  ('emerge', '美秀集團', 0),
  ('emerge', 'deca joins', 1),
  ('emerge', 'JAURIM', 2),
  ('emerge', '터치드(TOUCHED)', 3),
  ('emerge', '滅火器 Fire EX.', 4),
  ('emerge', '麋先生 MIXER', 5),
  ('emerge', '怕胖團 PAPUN BAND', 6),
  ('emerge', 'フレデリック(FREDERIC)', 7),
  ('emerge', 'go!go!vanillas', 8),
  ('emerge', 'The Chairs 椅子樂團', 9),
  ('emerge', '芒果醬 MangoJump', 10),
  ('emerge', '溫蒂漫步 Wendy Wander × Billyrrom', 11),
  ('emerge', '我是機車少女 I’mdifficult', 12),
  ('emerge', '拍謝少年 Sorry Youth', 13),
  ('emerge', '傻子與白痴', 14),
  ('emerge', 'Dragon Pony', 15),
  ('emerge', '旺福', 16),
  ('emerge', 'VH', 17),
  ('emerge', 'すりぃ THREEE', 18),
  ('emerge', 'とた(Tota)', 19),
  ('emerge', 'Cosmo’s Midnight', 20),
  ('emerge', 'SERIOUS BACON', 21),
  ('emerge', 'pami', 22),
  ('emerge', 'the cabs', 23),
  ('emerge', '音羽-otoha-', 24),
  ('emerge', '溫室雜草', 25),
  ('emerge', '庸俗救星', 26),
  ('emerge', '公館青少年', 27),
  ('emerge', 'P!SCO', 28),
  ('emerge', '粗大Band', 29),
  ('emerge', 'Haku.', 30),
  ('emerge', 'チョーキューメイ（Cho Q May）', 31),
  ('emerge', 'berry meet', 32),
  ('emerge', '원위(ONEWE)', 33),
  ('emerge', 'Redoor', 34),
  ('emerge', 'CAN’T BE BLUE', 35),
  ('emerge', 'kurayamisaka', 36),
  ('emerge', '雪国', 37),
  ('emerge', 'Ghost Bookstore', 38),
  ('emerge', 'SHOOTUP', 39),
  ('emerge', '梁河懸', 40),
  ('emerge', '孤獨的利裡', 41),
  ('emerge', 'REJAY', 42),
  ('emerge', '本能實業', 43),
  ('emerge', '凹與山', 44),
  ('emerge', 'JOYCE就以斯', 45),
  ('emerge', '野巢 Nosu', 46),
  ('emerge', 'KIK', 47),
  ('emerge', '林潔心', 48),
  ('emerge', '震樂堂 ft. 老諾', 49),
  ('emerge', 'パスピエ PASSEPIED', 50),
  ('emerge', 'INUWASI', 51),
  ('emerge', 'Quubi with 九尾Band', 52),
  ('emerge', 'NEO JAPONISM', 53),
  ('emerge', 'yosugala', 54),
  ('emerge', 'soda shower!', 55),
  ('emerge', 'Pure makeR', 56),
  ('emerge', '月宵◇クレシェンテ', 57),
  ('emerge', 'THEΔRAREz', 58),
  ('emerge', 'Happy Holiday!!', 59),
  ('emerge', 'debloop', 60),
  ('emerge', '共振效應', 61),
  ('emerge', 'Hammer Head Shark', 62),
  ('emerge', '3markets[ ]', 63),
  ('emerge', '薄暮 EVENFALL', 64),
  ('emerge', '憂憂 Yō-Yō', 65),
  ('emerge', 'sucola', 66),
  ('emerge', '隨性Random', 67),
  ('emerge', '上山', 68),
  ('emerge', '步行者 Pacers', 69),
  ('emerge', 'Black petrol', 70),
  ('emerge', 'Wantamnam 我地希望', 71),
  ('emerge', 'Night Keepers 守夜人 ft. XinU', 72),
  ('emerge', 'Kumu Basaw 姑慕.巴紹', 73),
  ('emerge', 'GOOD BYE APRIL', 74),
  ('emerge', 'liquid people', 75),
  ('emerge', 'GOODMOOD', 76),
  ('emerge', 'before the night ends', 77),
  ('emerge', '羊駝小姐 Malpaca', 78),
  ('emerge', '睿雞 RIKI', 79),
  ('emerge', 'Quanzo & O.Dkizzya', 80),
  ('emerge', 'Jimmy H. & HomeRich', 81),
  ('emerge', 'Lavi 翁彤薰', 82),
  ('emerge', 'O-VER-KiLL', 83),
  ('emerge', 'AKIRA KURØ', 84),

  -- 北野祭 (pp-festival)
  ('pp-festival', 'icyball 冰球樂團', 0),
  ('pp-festival', '庸俗救星', 1),
  ('pp-festival', 'Miao Miao Flow', 2),
  ('pp-festival', '李嫣', 3),
  ('pp-festival', 'Niki the Unicorn', 4),
  ('pp-festival', 'Hernia', 5),
  ('pp-festival', '逐火', 6),
  ('pp-festival', '迷霧森林樂團', 7),
  ('pp-festival', '泊人ANKR(DJ Gazer、DJ Bo Yin、DJ XIXI)', 8),

  -- 雨山祭 (yushan)
  ('yushan', '體熊專科', 0),
  ('yushan', '一種心情', 1),
  ('yushan', 'That’s My Shhh', 2),
  ('yushan', '無妄合作社', 3),
  ('yushan', '馬克SAVAGEM', 4),
  ('yushan', 'OBSESS', 5),
  ('yushan', '傷心欲絕', 6),
  ('yushan', 'debloop', 7),
  ('yushan', 'COLD DEW', 8),
  ('yushan', 'Who Cares 胡凱兒', 9),
  ('yushan', '傻子與白癡', 10),
  ('yushan', '百合花', 11),

  -- 卡卡音樂祭 (kaka)
  ('kaka', '福夢 FUMON', 0),
  ('kaka', '溫室雜草', 1),
  ('kaka', '好樂團', 2),
  ('kaka', '公館青少年', 3),
  ('kaka', '魚條 FISH STICK', 4),
  ('kaka', '傷心欲絕', 5),
  ('kaka', '浪犬 BillowMutt', 6),
  ('kaka', '康士坦的變化球 KST', 7),
  ('kaka', '忘憂水 Wonder Water', 8),
  ('kaka', 'VH', 9),
  ('kaka', 'hue', 10),
  ('kaka', '莉莉周她說', 11),
  ('kaka', '滅火器 Fire EX.', 12),
  ('kaka', 'DSPS', 13),

  -- 大港開唱 (megaport)
  ('megaport', 'Infernal Chaos', 0),
  ('megaport', '陽帆', 1),
  ('megaport', 'AiNA THE END', 2),
  ('megaport', '結束バンド KESSOKU BAND (JP)', 3),
  ('megaport', '落日飛車', 4),
  ('megaport', '滅火器 Fire EX.', 5),
  ('megaport', '康士坦的變化球 KST', 6),
  ('megaport', '椅子樂團', 7),
  ('megaport', '當代電影大師', 8),
  ('megaport', 'ゲシュタルト乙女 (urban session) ft. yurinasia', 9),
  ('megaport', 'ゲシュタルト乙女 (urban session) ft. yurinasia (JP)', 10),
  ('megaport', '隨性 ft. 婷文', 11),
  ('megaport', 'Cat’s Bile', 12),
  ('megaport', '共振效應', 13),
  ('megaport', 'Same Sam But Different ( Samjoo 鄭敬儒 X someshiit 山姆 X Sam Yang 楊世暄 )', 14),
  ('megaport', '拍謝少年', 15),
  ('megaport', 'NOVELISTS', 16),
  ('megaport', 'BAND-MAID', 17),
  ('megaport', '怕胖團', 18),
  ('megaport', '無妄合作社', 19),
  ('megaport', 'FunkyMo FunkyMo feat. 小尾巴', 20),
  ('megaport', '小尾巴', 21),
  ('megaport', '粉紅噪音', 22),
  ('megaport', '忘憂水 Wonder Water', 23),
  ('megaport', '打倒三明治', 24),
  ('megaport', 'COLD DEW', 25),
  ('megaport', '倒車入庫 R.I.G', 26),
  ('megaport', '陳以恆', 27),
  ('megaport', 'LEIGHT NINE', 28),
  ('megaport', '帕崎拉 PACHILA', 29),
  ('megaport', 'The Birthday (Kazuyuki Kuhara, Haruki Hirai, Kenji Fujii)', 30),
  ('megaport', 'the band apart', 31),
  ('megaport', '南瓜妮歌迷俱樂部', 32),
  ('megaport', '漂流出口 Outlet Drift', 33),
  ('megaport', 'DSPS', 34),
  ('megaport', 'KINAKO & 東京中央線', 35),
  ('megaport', '薄荷葉 ft. JB', 36),
  ('megaport', '黃宇寒 Han', 37),
  ('megaport', '沈默紳士 Silent Gentlemen', 38),
  ('megaport', 'LAWA', 39),
  ('megaport', 'Angie安吉', 40),
  ('megaport', 'MOTIF HIVE', 41),
  ('megaport', 'Crescent Lament', 42),
  ('megaport', '畫室The WLTZ', 43),
  ('megaport', '鄭宜農', 44),
  ('megaport', 'EmptyORio', 45),
  ('megaport', 'HUSH', 46),
  ('megaport', 'TOOBOE', 47),
  ('megaport', 'イルカポリス 海豚刑警', 48),
  ('megaport', 'TSS', 49),
  ('megaport', 'Yappy', 50),
  ('megaport', 'Yokkorio', 51),
  ('megaport', '多米多羅 ft, 可凡', 52),
  ('megaport', '體熊專科。Major in Body Bear', 53),
  ('megaport', '黃雨晴', 54),
  ('megaport', '震樂堂 JhenYueTang', 55),
  ('megaport', '洪安妮 Anni Hung', 56),
  ('megaport', '美麗本人 ft. 異鄉人', 57),
  ('megaport', '馬尾 ft. 立長', 58),
  ('megaport', '黑狼人肉戰車那卡西', 59),
  ('megaport', 'Käärijä', 60),
  ('megaport', '芒果醬 Mango Jump', 61),
  ('megaport', '庵心自在所', 62),
  ('megaport', 'debloop', 63),
  ('megaport', 'Manic Sheep', 64),
  ('megaport', 'P!SCO', 65),
  ('megaport', 'BBFFMF', 66),
  ('megaport', 'Mong Tong x XTRUX', 67),
  ('megaport', 'jo0ji', 68),
  ('megaport', 'Aooo', 69),
  ('megaport', 'milet', 70),
  ('megaport', '喜劇開港單口喜劇', 71),
  ('megaport', 'Gummy B', 72),
  ('megaport', '妮妃雅・瘋', 73),
  ('megaport', '李竺芯', 74),
  ('megaport', '宅邦戰隊 OTAKUNI 學園祭', 75),
  ('megaport', 'MoonD’shake', 76),
  ('megaport', '憂憂 ft 奕碩', 77),
  ('megaport', '《大象體操：比夢境更真實》紀錄長片', 78),
  ('megaport', '馬克 SAVAGE.Ｍ', 79),
  ('megaport', '昭霖 & 甜吻吻', 80),
  ('megaport', 'Plutato', 81),
  ('megaport', 'AVRALIZE', 82),
  ('megaport', '巨大的轟鳴', 83),
  ('megaport', '壓滿俱樂部', 84),
  ('megaport', '破地獄 Scattered Purgatory', 85),
  ('megaport', '謝明諺', 86),
  ('megaport', '羅百吉 ft. 寶貝', 87),
  ('megaport', '陳亞蘭', 88),
  ('megaport', 'NEE', 89),
  ('megaport', '謝金燕', 90),
  ('megaport', '何勁旻', 91),
  ('megaport', '陳冠哼', 92),
  ('megaport', '光頭火鳥', 93),
  ('megaport', '光頭珞亦', 94),
  ('megaport', '曾國宏', 95),
  ('megaport', '許正泰', 96),
  ('megaport', '寰宇龍虎豹', 97),
  ('megaport', '柯家洋', 98),
  ('megaport', '阿舌', 99),
  ('megaport', '小堯', 100),
  ('megaport', '阿賢', 101),
  ('megaport', 'DJ N.OERS', 102),
  ('megaport', 'DJ GAN3DA', 103),
  ('megaport', 'DJ GTER', 104),
  ('megaport', 'DJ YU', 105),
  ('megaport', 'DJ DINDIN', 106),
  ('megaport', 'C.Holly', 107),
  ('megaport', '五月五日OWALLOIL', 108),
  ('megaport', 'DJ QuestionMark', 109),
  ('megaport', 'DCIV', 110),
  ('megaport', 'Robot Swing', 111),
  ('megaport', 'Lazy Habits', 112),
  ('megaport', 'Flowstrong', 113),
  ('megaport', 'Dac', 114),
  ('megaport', 'FRαNKIE阿法', 115),
  ('megaport', 'LEO37', 116),
  ('megaport', 'DJ賴皮 MR.SKIN', 117),
  ('megaport', 'BRADD', 118),

  -- 台灣祭 (tmf)
  ('tmf', 'ROTTENGRAFFTY(JP)', 0),
  ('tmf', '盧廣仲', 1),
  ('tmf', '周湯豪NICKTHEREAL', 2),
  ('tmf', '滅火器Fire EX.', 3),
  ('tmf', '怕胖團 PAPUN BAND', 4),
  ('tmf', 'deca joins', 5),
  ('tmf', 'The Dinosaur’s Skin 恐龍的皮', 6),
  ('tmf', '傻子與白痴', 7),
  ('tmf', 'babychair(MY)', 8),
  ('tmf', 'LOSTAGE(JP)', 9),
  ('tmf', '南西肯恩', 10),
  ('tmf', 'EGG BRAIN(JP)', 11),
  ('tmf', '四星球(JP）', 12),
  ('tmf', '福夢FUMON', 13),
  ('tmf', '八十八顆芭樂籽', 14),
  ('tmf', '溫室雜草', 15),
  ('tmf', '無妄合作社', 16),
  ('tmf', '宋德鶴', 17),
  ('tmf', 'TRAGEDY OF MURDER（TH）', 18),
  ('tmf', '固定客Ft.馬克 SAVAGE.M', 19),
  ('tmf', '粗大Band', 20),
  ('tmf', 'SpecialThanks (JP)', 21),
  ('tmf', 'Multiverse Music(M.V.M) Ft. 百合花', 22),
  ('tmf', 'PIZZALI', 23),
  ('tmf', '林可綸AcRoss', 24),
  ('tmf', 'Frankie Paris(JP)', 25),
  ('tmf', 'Zunggu Zunggu(JP)', 26),
  ('tmf', 'YAPPY', 27),
  ('tmf', 'C.Holly', 28),
  ('tmf', 'Sabrina胡恂舞', 29),
  ('tmf', '西屯純愛組', 30),
  ('tmf', 'SADOG', 31),
  ('tmf', 'P!SCO Ft.海洋家族', 32),
  ('tmf', '閃閃閃閃', 33),
  ('tmf', '葵剛 Kuei Gang', 34),
  ('tmf', '林頤原 Euan', 35),
  ('tmf', '夕陽武士', 36),
  ('tmf', '胖虎 punkhoo', 37),
  ('tmf', 'EmptyORio', 38),
  ('tmf', 'SHOOTUP', 39),
  ('tmf', '普通隊長 Captain Ordinary', 40),
  ('tmf', '擊沈女孩 DESTROYERS', 41),
  ('tmf', '帕崎拉 PACHILA', 42),
  ('tmf', 'The Salitus', 43),
  ('tmf', '眠氣Hypersomnia', 44),
  ('tmf', '男子漢樂團', 45),
  ('tmf', 'KoOk 庫克', 46),
  ('tmf', '頂加集會', 47),
  ('tmf', 'OBSESS', 48),
  ('tmf', '步行者', 49),
  ('tmf', 'Traveller旅人', 50),
  ('tmf', '薄暮EVENFALL', 51),
  ('tmf', '工口紳士Ero Gent', 52),
  ('tmf', 'DrunkMonk 撞克茫客', 53),
  ('tmf', 'BUTTER RIOT', 54),
  ('tmf', '紙鳶', 55),
  ('tmf', 'SONNIE桑尼', 56),
  ('tmf', '核果人NUTS', 57),
  ('tmf', 'The Broken Flowers 碎紙花', 58),
  ('tmf', '海岸乾杯', 59),
  ('tmf', 'NeaR Band你阿伯', 60),
  ('tmf', 'Tickle Tickle癢癢', 61),
  ('tmf', '應聲倒地', 62),
  ('tmf', '等阮返來', 63),
  ('tmf', '夢遊旅人', 64),
  ('tmf', 'BELISH', 65),
  ('tmf', '吾橋有水 FloofingBridge', 66),
  ('tmf', '白頻率 whitefrequency', 67),
  ('tmf', 'Slowing Oscillation 斯洛頻率', 68),
  ('tmf', '沈默紳士', 69),
  ('tmf', '羊駝小姐', 70),
  ('tmf', 'Jairo (JP)', 71),
  ('tmf', 'Jene (JP)', 72),
  ('tmf', 'c8ight陳全', 73),
  ('tmf', '潤少', 74),
  ('tmf', 'LilHAO', 75),
  ('tmf', '潘潘潘博均PoinPan', 76),
  ('tmf', 'Quanzo & O.Dkizzya', 77),
  ('tmf', '鳥來啊MOB', 78),
  ('tmf', '大成', 79),
  ('tmf', 'Juice Boy', 80),
  ('tmf', '潮州土狗', 81),
  ('tmf', 'Peatle', 82),
  ('tmf', '𝗚𝟮𝗦𝗟𝗦 孤兒收容所', 83),
  ('tmf', 'DJ R Pon', 84),
  ('tmf', 'Young Lee', 85),
  ('tmf', 'DJ SamuelMie', 86),
  ('tmf', 'FRαNKIE阿法', 87),
  ('tmf', '馬克SAVAGE.M', 88),
  ('tmf', 'DJ 金剛', 89),
  ('tmf', 'Afuro George光學虎鯨', 90),
  ('tmf', '宇宙資料庫', 91),
  ('tmf', 'emoment', 92),
  ('tmf', '洛奇洛克 Rocket Rock', 93),
  ('tmf', 'Dragon Smash 龍族扣殺', 94),
  ('tmf', 'RIKI', 95),
  ('tmf', '槍擊艾拉 Change Era', 96),
  ('tmf', '好國民', 97),
  ('tmf', '鯊魚煙囪 Shark Chimney', 98),
  ('tmf', '無極西瓜刀', 99),
  ('tmf', '伯爵先生', 100),
  ('tmf', '遠鄉人 The Drifter', 101),
  ('tmf', '秋山ChillSome', 102),
  ('tmf', 'DiePression', 103),
  ('tmf', 'おとなりアイニー（JP）', 104),
  ('tmf', '22.5', 105),
  ('tmf', '青原FIDA（MO）', 106),
  ('tmf', '少年A', 107),
  ('tmf', '時不我予 AsTimeGoesBy', 108),
  ('tmf', 'Hedgehog (HK）', 109),
  ('tmf', '烈鷹', 110),
  ('tmf', 'CB狗 (SG)', 111),
  ('tmf', '鯊魚娃娃機ToyShark', 112),
  ('tmf', '油漬艾莉', 113),
  ('tmf', '貓拳', 114),
  ('tmf', '慶記KTV（YU、Double K、男模小晉、羅曼迪克、KOALA WU）', 115),
  ('tmf', 'NEWKIDSTOWN （TIPSY、KUOKUO、AJi、Denzel Cheng）', 116),
  ('tmf', '動漫派', 117),
  ('tmf', 'Ku da Yeast', 118),
  ('tmf', '和同開心', 119),

  -- 屏東三大日音樂節 (pingtung-3days)
  ('pingtung-3days', '孝琳 HYOLYN', 0),
  ('pingtung-3days', '韋禮安', 1),
  ('pingtung-3days', '美秀集團', 2),
  ('pingtung-3days', 'WhoCares 胡凱兒', 3),
  ('pingtung-3days', '公館青少年', 4),
  ('pingtung-3days', '李竺芯', 5),
  ('pingtung-3days', '粗大Band', 6),
  ('pingtung-3days', '怕胖團', 7),
  ('pingtung-3days', '陳忻玥', 8),
  ('pingtung-3days', '王艷薇', 9),
  ('pingtung-3days', 'someshiit 山姆', 10),
  ('pingtung-3days', '沈文程', 11),
  ('pingtung-3days', '藍又時', 12),
  ('pingtung-3days', '亦帆', 13),
  ('pingtung-3days', '曾瑋中', 14),
  ('pingtung-3days', '蔡秋鳳', 15),

  -- 政大夏日祭典 (nccu-summer)
  ('nccu-summer', 'Sabrina 胡恂舞', 0),
  ('nccu-summer', '公館青少年', 1),
  ('nccu-summer', '甜約翰', 2),
  ('nccu-summer', '呂允', 3),
  ('nccu-summer', 'JOYCE 就以斯', 4),
  ('nccu-summer', '南西肯恩', 5),

  -- 西拉雅森活節草原音樂祭 (siraya)
  ('siraya', '白頻率', 0),
  ('siraya', 'BIKE機踏車樂團', 1),
  ('siraya', '步行者', 2),
  ('siraya', '芒果醬', 3),
  ('siraya', '余凱揚', 4),
  ('siraya', '林喬安', 5),
  ('siraya', '許志豪', 6),
  ('siraya', '翁鈺鈞', 7),
  ('siraya', '陳孟賢', 8),

  -- 東浪嘉年華 (east-wave)
  ('east-wave', 'ØZI', 0),
  ('east-wave', 'Karencici', 1),
  ('east-wave', '楊乃文', 2),
  ('east-wave', '周湯豪', 3),
  ('east-wave', '李英宏', 4),
  ('east-wave', '沈文程', 5),
  ('east-wave', '孫淑媚', 6),
  ('east-wave', '安心亞', 7),
  ('east-wave', '宇宙人', 8),
  ('east-wave', '理想混蛋', 9),
  ('east-wave', '麋先生', 10),
  ('east-wave', 'Slapkiss', 11),
  ('east-wave', 'someshit山姆', 12),
  ('east-wave', '公館青少年', 13),

  -- 愛嶼搖滾 (love-rock)
  ('love-rock', 'Who Cares 胡凱兒', 0),
  ('love-rock', 'P!SCO ft 海洋家族', 1),
  ('love-rock', 'SHOOTUP', 2),
  ('love-rock', '普通隊長 Captain Ordinary', 3),
  ('love-rock', 'Maki (JP)', 4),
  ('love-rock', 'KUZIRA (JP)', 5),
  ('love-rock', '血肉果汁機', 6),
  ('love-rock', '貓魚娃娃機', 7),
  ('love-rock', '廢墟倒地', 8),
  ('love-rock', '羊米人', 9),
  ('love-rock', '核果人NUTS', 10),
  ('love-rock', '白頻率', 11),
  ('love-rock', '薄暮', 12),
  ('love-rock', '眠氣 Hypersomnia', 13),
  ('love-rock', '白色校際聯演', 14),
  ('love-rock', '海岸乾杯', 15),
  ('love-rock', '昴宿', 16),
  ('love-rock', 'The Salitus', 17),
  ('love-rock', '少年A', 18),
  ('love-rock', 'Allen Avenge 異族亡魂', 19),
  ('love-rock', '文明人 The Civilized 校際聯演特別演出', 20),
  ('love-rock', 'イルカポリス 海豚刑警', 21),
  ('love-rock', '唐俗救星', 22),
  ('love-rock', '旅人', 23),
  ('love-rock', '固定客', 24),
  ('love-rock', '福夢FUMON', 25),
  ('love-rock', '無妄合作社', 26),
  ('love-rock', '傷心欲絕', 27),
  ('love-rock', 'blu mush', 28),
  ('love-rock', '宇宙資料庫', 29),
  ('love-rock', '畫室', 30),
  ('love-rock', '秋波愛麗', 31),
  ('love-rock', '等阮返來', 32),
  ('love-rock', '咱不我予', 33),
  ('love-rock', '秋山', 34),
  ('love-rock', '微醺龐克', 35),
  ('love-rock', '伯爵先生', 36),
  ('love-rock', '蔗嗚子', 37),
  ('love-rock', 'Hbun 河紋', 38),
  ('love-rock', 'RIKI', 39),
  ('love-rock', '烈鷹', 40),
  ('love-rock', 'Snake 潘阿閔', 41),

  -- 赤聲躁動音樂祭 (hot-wave)
  ('hot-wave', '怕胖團 PAPUN BAND', 0),
  ('hot-wave', '血肉果汁機', 1),
  ('hot-wave', '芒果醬 Mango Jump', 2),
  ('hot-wave', '福夢 FUMON', 3),
  ('hot-wave', '溫室雜草', 4),
  ('hot-wave', 'INFERNAL CHAOS', 5),
  ('hot-wave', '庸俗救星 Vulgar Savior', 6),
  ('hot-wave', '紙鳶 Seizer', 7),
  ('hot-wave', 'Triple Deer', 8),
  ('hot-wave', '工口紳士 Ero Gent', 9),
  ('hot-wave', 'Xmoraz', 10),
  ('hot-wave', '碎紙花', 11),
  ('hot-wave', 'HOLOTROPICS', 12),
  ('hot-wave', '羊米人 YUMMY MAN', 13),
  ('hot-wave', 'Soul Sorry', 14),
  ('hot-wave', 'HYANG [KR]', 15),
  ('hot-wave', 'IRIS MONDO [JP]', 16),
  ('hot-wave', 'リュックと添い寝ごはん ryukku to soine gohan [JP]', 17),
  ('hot-wave', 'kiyu [JP]', 18),
  ('hot-wave', 'The Publish [TH]', 19),
  ('hot-wave', 'Aggressive Raisin Cat [SG]', 20),
  ('hot-wave', 'icyball 冰球樂團', 21),
  ('hot-wave', '溫蒂漫步 Wendy Wander', 22),
  ('hot-wave', 'wannasleep', 23),
  ('hot-wave', '公館青少年 GGteens', 24),
  ('hot-wave', '震樂堂', 25),
  ('hot-wave', '薄暮 EVENFALL', 26),
  ('hot-wave', '175R [JP]', 27),
  ('hot-wave', 'the engy [JP]', 28),
  ('hot-wave', 'pachae [JP]', 29),
  ('hot-wave', 'ギョウザマン GYOZAMAN [JP]', 30),
  ('hot-wave', 'FLAPSTAR [JP]', 31),
  ('hot-wave', 'THEΔRAREz', 32),
  ('hot-wave', '終焉Rebirth', 33),
  ('hot-wave', '국카스텐 Guckkasten [KR]', 34),
  ('hot-wave', '신인류 Shin In Ryu [KR]', 35),
  ('hot-wave', '해서웨이 hathaw9y [KR]', 36),
  ('hot-wave', '다다다 DADADA [KR]', 37),

  -- 春浪音樂節 (spring-wave)
  ('spring-wave', 'MEMI', 0),
  ('spring-wave', 'PeaceHotel 和平飯店', 1),
  ('spring-wave', '怕胖團 PAPUN BAND', 2),
  ('spring-wave', '康士坦的變化球 KST', 3),
  ('spring-wave', '傻子與白痴', 4),
  ('spring-wave', '溫室雜草', 5),
  ('spring-wave', '宋德鶴', 6),
  ('spring-wave', 'Lizi 栗子', 7),
  ('spring-wave', '慶記KTV-DJ Double K ft.小鐘', 8),
  ('spring-wave', '陳土豆', 9),
  ('spring-wave', '生祥樂隊', 10),
  ('spring-wave', '八三夭', 11),
  ('spring-wave', 'someshiit 山姆', 12),
  ('spring-wave', 'Multiverse Music', 13),
  ('spring-wave', '荒山茉莉', 14),
  ('spring-wave', 'SONNIE 桑尼', 15),
  ('spring-wave', '浪漫里', 16),
  ('spring-wave', '面白大丈夫 - 搞笑救星', 17),
  ('spring-wave', '愛希頌缽', 18),
  ('spring-wave', '看我笑話工作室', 19),
  ('spring-wave', '峸劇場 - BarART原創酒吧劇集', 20),
  ('spring-wave', 'EOM', 21),
  ('spring-wave', 'Omoinotake', 22),
  ('spring-wave', '告五人', 23),
  ('spring-wave', 'TRASH', 24),
  ('spring-wave', 'Karencici', 25),
  ('spring-wave', '芒果醬 Mango Jump', 26),
  ('spring-wave', '福夢 FUMON', 27),
  ('spring-wave', '百合花 Lilium', 28),
  ('spring-wave', '鳳小岳', 29),
  ('spring-wave', 'MONO NO AWARE', 30),
  ('spring-wave', '陳嫺靜', 31),
  ('spring-wave', '黃宇寒 Han', 32),
  ('spring-wave', '莉莉周她說 Lily Chou-Chou Lied', 33),
  ('spring-wave', '米莎Misa & 早川徹', 34),
  ('spring-wave', '粹垢 TRAEGO', 35),
  ('spring-wave', '核果人NUTS', 36),
  ('spring-wave', '宅邦戰隊', 37),
  ('spring-wave', 'TriForm', 38),

  -- 火球祭 (fireball)：陣容待公布，先以佔位藝人呈現。
  ('fireball', '待公布', 0)
)
insert into public.artists (name)
select distinct artist_name
from lineup
on conflict (name) do nothing;

-- 推導 festival_artists（用名稱 join 取得 artist id，重跑也安全）
with lineup (festival_id, artist_name, position) as (
  values
  -- 龍虎門 247 音樂日 (lunghumen-247)
  ('lunghumen-247', '滿人Manchuker', 0),
  ('lunghumen-247', 'J.Sheon', 1),
  ('lunghumen-247', '熊仔 Kumachan', 2),
  ('lunghumen-247', '健志 KEN-G', 3),
  ('lunghumen-247', '美麗本人', 4),
  ('lunghumen-247', '婁峻碩SHOU', 5),
  ('lunghumen-247', '呂士軒 Trout Fresh', 6),
  ('lunghumen-247', 'Barry Chen', 7),
  ('lunghumen-247', 'Gummy B', 8),
  ('lunghumen-247', 'M.V.M', 9),
  ('lunghumen-247', 'SHIGGA SHAY 西閣', 10),
  ('lunghumen-247', '潤少', 11),
  ('lunghumen-247', 'LilHAO', 12),
  ('lunghumen-247', '吳霏', 13),

  -- 浮現祭 (emerge)
  ('emerge', '美秀集團', 0),
  ('emerge', 'deca joins', 1),
  ('emerge', 'JAURIM', 2),
  ('emerge', '터치드(TOUCHED)', 3),
  ('emerge', '滅火器 Fire EX.', 4),
  ('emerge', '麋先生 MIXER', 5),
  ('emerge', '怕胖團 PAPUN BAND', 6),
  ('emerge', 'フレデリック(FREDERIC)', 7),
  ('emerge', 'go!go!vanillas', 8),
  ('emerge', 'The Chairs 椅子樂團', 9),
  ('emerge', '芒果醬 MangoJump', 10),
  ('emerge', '溫蒂漫步 Wendy Wander × Billyrrom', 11),
  ('emerge', '我是機車少女 I’mdifficult', 12),
  ('emerge', '拍謝少年 Sorry Youth', 13),
  ('emerge', '傻子與白痴', 14),
  ('emerge', 'Dragon Pony', 15),
  ('emerge', '旺福', 16),
  ('emerge', 'VH', 17),
  ('emerge', 'すりぃ THREEE', 18),
  ('emerge', 'とた(Tota)', 19),
  ('emerge', 'Cosmo’s Midnight', 20),
  ('emerge', 'SERIOUS BACON', 21),
  ('emerge', 'pami', 22),
  ('emerge', 'the cabs', 23),
  ('emerge', '音羽-otoha-', 24),
  ('emerge', '溫室雜草', 25),
  ('emerge', '庸俗救星', 26),
  ('emerge', '公館青少年', 27),
  ('emerge', 'P!SCO', 28),
  ('emerge', '粗大Band', 29),
  ('emerge', 'Haku.', 30),
  ('emerge', 'チョーキューメイ（Cho Q May）', 31),
  ('emerge', 'berry meet', 32),
  ('emerge', '원위(ONEWE)', 33),
  ('emerge', 'Redoor', 34),
  ('emerge', 'CAN’T BE BLUE', 35),
  ('emerge', 'kurayamisaka', 36),
  ('emerge', '雪国', 37),
  ('emerge', 'Ghost Bookstore', 38),
  ('emerge', 'SHOOTUP', 39),
  ('emerge', '梁河懸', 40),
  ('emerge', '孤獨的利裡', 41),
  ('emerge', 'REJAY', 42),
  ('emerge', '本能實業', 43),
  ('emerge', '凹與山', 44),
  ('emerge', 'JOYCE就以斯', 45),
  ('emerge', '野巢 Nosu', 46),
  ('emerge', 'KIK', 47),
  ('emerge', '林潔心', 48),
  ('emerge', '震樂堂 ft. 老諾', 49),
  ('emerge', 'パスピエ PASSEPIED', 50),
  ('emerge', 'INUWASI', 51),
  ('emerge', 'Quubi with 九尾Band', 52),
  ('emerge', 'NEO JAPONISM', 53),
  ('emerge', 'yosugala', 54),
  ('emerge', 'soda shower!', 55),
  ('emerge', 'Pure makeR', 56),
  ('emerge', '月宵◇クレシェンテ', 57),
  ('emerge', 'THEΔRAREz', 58),
  ('emerge', 'Happy Holiday!!', 59),
  ('emerge', 'debloop', 60),
  ('emerge', '共振效應', 61),
  ('emerge', 'Hammer Head Shark', 62),
  ('emerge', '3markets[ ]', 63),
  ('emerge', '薄暮 EVENFALL', 64),
  ('emerge', '憂憂 Yō-Yō', 65),
  ('emerge', 'sucola', 66),
  ('emerge', '隨性Random', 67),
  ('emerge', '上山', 68),
  ('emerge', '步行者 Pacers', 69),
  ('emerge', 'Black petrol', 70),
  ('emerge', 'Wantamnam 我地希望', 71),
  ('emerge', 'Night Keepers 守夜人 ft. XinU', 72),
  ('emerge', 'Kumu Basaw 姑慕.巴紹', 73),
  ('emerge', 'GOOD BYE APRIL', 74),
  ('emerge', 'liquid people', 75),
  ('emerge', 'GOODMOOD', 76),
  ('emerge', 'before the night ends', 77),
  ('emerge', '羊駝小姐 Malpaca', 78),
  ('emerge', '睿雞 RIKI', 79),
  ('emerge', 'Quanzo & O.Dkizzya', 80),
  ('emerge', 'Jimmy H. & HomeRich', 81),
  ('emerge', 'Lavi 翁彤薰', 82),
  ('emerge', 'O-VER-KiLL', 83),
  ('emerge', 'AKIRA KURØ', 84),

  -- 北野祭 (pp-festival)
  ('pp-festival', 'icyball 冰球樂團', 0),
  ('pp-festival', '庸俗救星', 1),
  ('pp-festival', 'Miao Miao Flow', 2),
  ('pp-festival', '李嫣', 3),
  ('pp-festival', 'Niki the Unicorn', 4),
  ('pp-festival', 'Hernia', 5),
  ('pp-festival', '逐火', 6),
  ('pp-festival', '迷霧森林樂團', 7),
  ('pp-festival', '泊人ANKR(DJ Gazer、DJ Bo Yin、DJ XIXI)', 8),

  -- 雨山祭 (yushan)
  ('yushan', '體熊專科', 0),
  ('yushan', '一種心情', 1),
  ('yushan', 'That’s My Shhh', 2),
  ('yushan', '無妄合作社', 3),
  ('yushan', '馬克SAVAGEM', 4),
  ('yushan', 'OBSESS', 5),
  ('yushan', '傷心欲絕', 6),
  ('yushan', 'debloop', 7),
  ('yushan', 'COLD DEW', 8),
  ('yushan', 'Who Cares 胡凱兒', 9),
  ('yushan', '傻子與白癡', 10),
  ('yushan', '百合花', 11),

  -- 卡卡音樂祭 (kaka)
  ('kaka', '福夢 FUMON', 0),
  ('kaka', '溫室雜草', 1),
  ('kaka', '好樂團', 2),
  ('kaka', '公館青少年', 3),
  ('kaka', '魚條 FISH STICK', 4),
  ('kaka', '傷心欲絕', 5),
  ('kaka', '浪犬 BillowMutt', 6),
  ('kaka', '康士坦的變化球 KST', 7),
  ('kaka', '忘憂水 Wonder Water', 8),
  ('kaka', 'VH', 9),
  ('kaka', 'hue', 10),
  ('kaka', '莉莉周她說', 11),
  ('kaka', '滅火器 Fire EX.', 12),
  ('kaka', 'DSPS', 13),

  -- 大港開唱 (megaport)
  ('megaport', 'Infernal Chaos', 0),
  ('megaport', '陽帆', 1),
  ('megaport', 'AiNA THE END', 2),
  ('megaport', '結束バンド KESSOKU BAND (JP)', 3),
  ('megaport', '落日飛車', 4),
  ('megaport', '滅火器 Fire EX.', 5),
  ('megaport', '康士坦的變化球 KST', 6),
  ('megaport', '椅子樂團', 7),
  ('megaport', '當代電影大師', 8),
  ('megaport', 'ゲシュタルト乙女 (urban session) ft. yurinasia', 9),
  ('megaport', 'ゲシュタルト乙女 (urban session) ft. yurinasia (JP)', 10),
  ('megaport', '隨性 ft. 婷文', 11),
  ('megaport', 'Cat’s Bile', 12),
  ('megaport', '共振效應', 13),
  ('megaport', 'Same Sam But Different ( Samjoo 鄭敬儒 X someshiit 山姆 X Sam Yang 楊世暄 )', 14),
  ('megaport', '拍謝少年', 15),
  ('megaport', 'NOVELISTS', 16),
  ('megaport', 'BAND-MAID', 17),
  ('megaport', '怕胖團', 18),
  ('megaport', '無妄合作社', 19),
  ('megaport', 'FunkyMo FunkyMo feat. 小尾巴', 20),
  ('megaport', '小尾巴', 21),
  ('megaport', '粉紅噪音', 22),
  ('megaport', '忘憂水 Wonder Water', 23),
  ('megaport', '打倒三明治', 24),
  ('megaport', 'COLD DEW', 25),
  ('megaport', '倒車入庫 R.I.G', 26),
  ('megaport', '陳以恆', 27),
  ('megaport', 'LEIGHT NINE', 28),
  ('megaport', '帕崎拉 PACHILA', 29),
  ('megaport', 'The Birthday (Kazuyuki Kuhara, Haruki Hirai, Kenji Fujii)', 30),
  ('megaport', 'the band apart', 31),
  ('megaport', '南瓜妮歌迷俱樂部', 32),
  ('megaport', '漂流出口 Outlet Drift', 33),
  ('megaport', 'DSPS', 34),
  ('megaport', 'KINAKO & 東京中央線', 35),
  ('megaport', '薄荷葉 ft. JB', 36),
  ('megaport', '黃宇寒 Han', 37),
  ('megaport', '沈默紳士 Silent Gentlemen', 38),
  ('megaport', 'LAWA', 39),
  ('megaport', 'Angie安吉', 40),
  ('megaport', 'MOTIF HIVE', 41),
  ('megaport', 'Crescent Lament', 42),
  ('megaport', '畫室The WLTZ', 43),
  ('megaport', '鄭宜農', 44),
  ('megaport', 'EmptyORio', 45),
  ('megaport', 'HUSH', 46),
  ('megaport', 'TOOBOE', 47),
  ('megaport', 'イルカポリス 海豚刑警', 48),
  ('megaport', 'TSS', 49),
  ('megaport', 'Yappy', 50),
  ('megaport', 'Yokkorio', 51),
  ('megaport', '多米多羅 ft, 可凡', 52),
  ('megaport', '體熊專科。Major in Body Bear', 53),
  ('megaport', '黃雨晴', 54),
  ('megaport', '震樂堂 JhenYueTang', 55),
  ('megaport', '洪安妮 Anni Hung', 56),
  ('megaport', '美麗本人 ft. 異鄉人', 57),
  ('megaport', '馬尾 ft. 立長', 58),
  ('megaport', '黑狼人肉戰車那卡西', 59),
  ('megaport', 'Käärijä', 60),
  ('megaport', '芒果醬 Mango Jump', 61),
  ('megaport', '庵心自在所', 62),
  ('megaport', 'debloop', 63),
  ('megaport', 'Manic Sheep', 64),
  ('megaport', 'P!SCO', 65),
  ('megaport', 'BBFFMF', 66),
  ('megaport', 'Mong Tong x XTRUX', 67),
  ('megaport', 'jo0ji', 68),
  ('megaport', 'Aooo', 69),
  ('megaport', 'milet', 70),
  ('megaport', '喜劇開港單口喜劇', 71),
  ('megaport', 'Gummy B', 72),
  ('megaport', '妮妃雅・瘋', 73),
  ('megaport', '李竺芯', 74),
  ('megaport', '宅邦戰隊 OTAKUNI 學園祭', 75),
  ('megaport', 'MoonD’shake', 76),
  ('megaport', '憂憂 ft 奕碩', 77),
  ('megaport', '《大象體操：比夢境更真實》紀錄長片', 78),
  ('megaport', '馬克 SAVAGE.Ｍ', 79),
  ('megaport', '昭霖 & 甜吻吻', 80),
  ('megaport', 'Plutato', 81),
  ('megaport', 'AVRALIZE', 82),
  ('megaport', '巨大的轟鳴', 83),
  ('megaport', '壓滿俱樂部', 84),
  ('megaport', '破地獄 Scattered Purgatory', 85),
  ('megaport', '謝明諺', 86),
  ('megaport', '羅百吉 ft. 寶貝', 87),
  ('megaport', '陳亞蘭', 88),
  ('megaport', 'NEE', 89),
  ('megaport', '謝金燕', 90),
  ('megaport', '何勁旻', 91),
  ('megaport', '陳冠哼', 92),
  ('megaport', '光頭火鳥', 93),
  ('megaport', '光頭珞亦', 94),
  ('megaport', '曾國宏', 95),
  ('megaport', '許正泰', 96),
  ('megaport', '寰宇龍虎豹', 97),
  ('megaport', '柯家洋', 98),
  ('megaport', '阿舌', 99),
  ('megaport', '小堯', 100),
  ('megaport', '阿賢', 101),
  ('megaport', 'DJ N.OERS', 102),
  ('megaport', 'DJ GAN3DA', 103),
  ('megaport', 'DJ GTER', 104),
  ('megaport', 'DJ YU', 105),
  ('megaport', 'DJ DINDIN', 106),
  ('megaport', 'C.Holly', 107),
  ('megaport', '五月五日OWALLOIL', 108),
  ('megaport', 'DJ QuestionMark', 109),
  ('megaport', 'DCIV', 110),
  ('megaport', 'Robot Swing', 111),
  ('megaport', 'Lazy Habits', 112),
  ('megaport', 'Flowstrong', 113),
  ('megaport', 'Dac', 114),
  ('megaport', 'FRαNKIE阿法', 115),
  ('megaport', 'LEO37', 116),
  ('megaport', 'DJ賴皮 MR.SKIN', 117),
  ('megaport', 'BRADD', 118),

  -- 台灣祭 (tmf)
  ('tmf', 'ROTTENGRAFFTY(JP)', 0),
  ('tmf', '盧廣仲', 1),
  ('tmf', '周湯豪NICKTHEREAL', 2),
  ('tmf', '滅火器Fire EX.', 3),
  ('tmf', '怕胖團 PAPUN BAND', 4),
  ('tmf', 'deca joins', 5),
  ('tmf', 'The Dinosaur’s Skin 恐龍的皮', 6),
  ('tmf', '傻子與白痴', 7),
  ('tmf', 'babychair(MY)', 8),
  ('tmf', 'LOSTAGE(JP)', 9),
  ('tmf', '南西肯恩', 10),
  ('tmf', 'EGG BRAIN(JP)', 11),
  ('tmf', '四星球(JP）', 12),
  ('tmf', '福夢FUMON', 13),
  ('tmf', '八十八顆芭樂籽', 14),
  ('tmf', '溫室雜草', 15),
  ('tmf', '無妄合作社', 16),
  ('tmf', '宋德鶴', 17),
  ('tmf', 'TRAGEDY OF MURDER（TH）', 18),
  ('tmf', '固定客Ft.馬克 SAVAGE.M', 19),
  ('tmf', '粗大Band', 20),
  ('tmf', 'SpecialThanks (JP)', 21),
  ('tmf', 'Multiverse Music(M.V.M) Ft. 百合花', 22),
  ('tmf', 'PIZZALI', 23),
  ('tmf', '林可綸AcRoss', 24),
  ('tmf', 'Frankie Paris(JP)', 25),
  ('tmf', 'Zunggu Zunggu(JP)', 26),
  ('tmf', 'YAPPY', 27),
  ('tmf', 'C.Holly', 28),
  ('tmf', 'Sabrina胡恂舞', 29),
  ('tmf', '西屯純愛組', 30),
  ('tmf', 'SADOG', 31),
  ('tmf', 'P!SCO Ft.海洋家族', 32),
  ('tmf', '閃閃閃閃', 33),
  ('tmf', '葵剛 Kuei Gang', 34),
  ('tmf', '林頤原 Euan', 35),
  ('tmf', '夕陽武士', 36),
  ('tmf', '胖虎 punkhoo', 37),
  ('tmf', 'EmptyORio', 38),
  ('tmf', 'SHOOTUP', 39),
  ('tmf', '普通隊長 Captain Ordinary', 40),
  ('tmf', '擊沈女孩 DESTROYERS', 41),
  ('tmf', '帕崎拉 PACHILA', 42),
  ('tmf', 'The Salitus', 43),
  ('tmf', '眠氣Hypersomnia', 44),
  ('tmf', '男子漢樂團', 45),
  ('tmf', 'KoOk 庫克', 46),
  ('tmf', '頂加集會', 47),
  ('tmf', 'OBSESS', 48),
  ('tmf', '步行者', 49),
  ('tmf', 'Traveller旅人', 50),
  ('tmf', '薄暮EVENFALL', 51),
  ('tmf', '工口紳士Ero Gent', 52),
  ('tmf', 'DrunkMonk 撞克茫客', 53),
  ('tmf', 'BUTTER RIOT', 54),
  ('tmf', '紙鳶', 55),
  ('tmf', 'SONNIE桑尼', 56),
  ('tmf', '核果人NUTS', 57),
  ('tmf', 'The Broken Flowers 碎紙花', 58),
  ('tmf', '海岸乾杯', 59),
  ('tmf', 'NeaR Band你阿伯', 60),
  ('tmf', 'Tickle Tickle癢癢', 61),
  ('tmf', '應聲倒地', 62),
  ('tmf', '等阮返來', 63),
  ('tmf', '夢遊旅人', 64),
  ('tmf', 'BELISH', 65),
  ('tmf', '吾橋有水 FloofingBridge', 66),
  ('tmf', '白頻率 whitefrequency', 67),
  ('tmf', 'Slowing Oscillation 斯洛頻率', 68),
  ('tmf', '沈默紳士', 69),
  ('tmf', '羊駝小姐', 70),
  ('tmf', 'Jairo (JP)', 71),
  ('tmf', 'Jene (JP)', 72),
  ('tmf', 'c8ight陳全', 73),
  ('tmf', '潤少', 74),
  ('tmf', 'LilHAO', 75),
  ('tmf', '潘潘潘博均PoinPan', 76),
  ('tmf', 'Quanzo & O.Dkizzya', 77),
  ('tmf', '鳥來啊MOB', 78),
  ('tmf', '大成', 79),
  ('tmf', 'Juice Boy', 80),
  ('tmf', '潮州土狗', 81),
  ('tmf', 'Peatle', 82),
  ('tmf', '𝗚𝟮𝗦𝗟𝗦 孤兒收容所', 83),
  ('tmf', 'DJ R Pon', 84),
  ('tmf', 'Young Lee', 85),
  ('tmf', 'DJ SamuelMie', 86),
  ('tmf', 'FRαNKIE阿法', 87),
  ('tmf', '馬克SAVAGE.M', 88),
  ('tmf', 'DJ 金剛', 89),
  ('tmf', 'Afuro George光學虎鯨', 90),
  ('tmf', '宇宙資料庫', 91),
  ('tmf', 'emoment', 92),
  ('tmf', '洛奇洛克 Rocket Rock', 93),
  ('tmf', 'Dragon Smash 龍族扣殺', 94),
  ('tmf', 'RIKI', 95),
  ('tmf', '槍擊艾拉 Change Era', 96),
  ('tmf', '好國民', 97),
  ('tmf', '鯊魚煙囪 Shark Chimney', 98),
  ('tmf', '無極西瓜刀', 99),
  ('tmf', '伯爵先生', 100),
  ('tmf', '遠鄉人 The Drifter', 101),
  ('tmf', '秋山ChillSome', 102),
  ('tmf', 'DiePression', 103),
  ('tmf', 'おとなりアイニー（JP）', 104),
  ('tmf', '22.5', 105),
  ('tmf', '青原FIDA（MO）', 106),
  ('tmf', '少年A', 107),
  ('tmf', '時不我予 AsTimeGoesBy', 108),
  ('tmf', 'Hedgehog (HK）', 109),
  ('tmf', '烈鷹', 110),
  ('tmf', 'CB狗 (SG)', 111),
  ('tmf', '鯊魚娃娃機ToyShark', 112),
  ('tmf', '油漬艾莉', 113),
  ('tmf', '貓拳', 114),
  ('tmf', '慶記KTV（YU、Double K、男模小晉、羅曼迪克、KOALA WU）', 115),
  ('tmf', 'NEWKIDSTOWN （TIPSY、KUOKUO、AJi、Denzel Cheng）', 116),
  ('tmf', '動漫派', 117),
  ('tmf', 'Ku da Yeast', 118),
  ('tmf', '和同開心', 119),

  -- 屏東三大日音樂節 (pingtung-3days)
  ('pingtung-3days', '孝琳 HYOLYN', 0),
  ('pingtung-3days', '韋禮安', 1),
  ('pingtung-3days', '美秀集團', 2),
  ('pingtung-3days', 'WhoCares 胡凱兒', 3),
  ('pingtung-3days', '公館青少年', 4),
  ('pingtung-3days', '李竺芯', 5),
  ('pingtung-3days', '粗大Band', 6),
  ('pingtung-3days', '怕胖團', 7),
  ('pingtung-3days', '陳忻玥', 8),
  ('pingtung-3days', '王艷薇', 9),
  ('pingtung-3days', 'someshiit 山姆', 10),
  ('pingtung-3days', '沈文程', 11),
  ('pingtung-3days', '藍又時', 12),
  ('pingtung-3days', '亦帆', 13),
  ('pingtung-3days', '曾瑋中', 14),
  ('pingtung-3days', '蔡秋鳳', 15),

  -- 政大夏日祭典 (nccu-summer)
  ('nccu-summer', 'Sabrina 胡恂舞', 0),
  ('nccu-summer', '公館青少年', 1),
  ('nccu-summer', '甜約翰', 2),
  ('nccu-summer', '呂允', 3),
  ('nccu-summer', 'JOYCE 就以斯', 4),
  ('nccu-summer', '南西肯恩', 5),

  -- 西拉雅森活節草原音樂祭 (siraya)
  ('siraya', '白頻率', 0),
  ('siraya', 'BIKE機踏車樂團', 1),
  ('siraya', '步行者', 2),
  ('siraya', '芒果醬', 3),
  ('siraya', '余凱揚', 4),
  ('siraya', '林喬安', 5),
  ('siraya', '許志豪', 6),
  ('siraya', '翁鈺鈞', 7),
  ('siraya', '陳孟賢', 8),

  -- 東浪嘉年華 (east-wave)
  ('east-wave', 'ØZI', 0),
  ('east-wave', 'Karencici', 1),
  ('east-wave', '楊乃文', 2),
  ('east-wave', '周湯豪', 3),
  ('east-wave', '李英宏', 4),
  ('east-wave', '沈文程', 5),
  ('east-wave', '孫淑媚', 6),
  ('east-wave', '安心亞', 7),
  ('east-wave', '宇宙人', 8),
  ('east-wave', '理想混蛋', 9),
  ('east-wave', '麋先生', 10),
  ('east-wave', 'Slapkiss', 11),
  ('east-wave', 'someshit山姆', 12),
  ('east-wave', '公館青少年', 13),

  -- 愛嶼搖滾 (love-rock)
  ('love-rock', 'Who Cares 胡凱兒', 0),
  ('love-rock', 'P!SCO ft 海洋家族', 1),
  ('love-rock', 'SHOOTUP', 2),
  ('love-rock', '普通隊長 Captain Ordinary', 3),
  ('love-rock', 'Maki (JP)', 4),
  ('love-rock', 'KUZIRA (JP)', 5),
  ('love-rock', '血肉果汁機', 6),
  ('love-rock', '貓魚娃娃機', 7),
  ('love-rock', '廢墟倒地', 8),
  ('love-rock', '羊米人', 9),
  ('love-rock', '核果人NUTS', 10),
  ('love-rock', '白頻率', 11),
  ('love-rock', '薄暮', 12),
  ('love-rock', '眠氣 Hypersomnia', 13),
  ('love-rock', '白色校際聯演', 14),
  ('love-rock', '海岸乾杯', 15),
  ('love-rock', '昴宿', 16),
  ('love-rock', 'The Salitus', 17),
  ('love-rock', '少年A', 18),
  ('love-rock', 'Allen Avenge 異族亡魂', 19),
  ('love-rock', '文明人 The Civilized 校際聯演特別演出', 20),
  ('love-rock', 'イルカポリス 海豚刑警', 21),
  ('love-rock', '唐俗救星', 22),
  ('love-rock', '旅人', 23),
  ('love-rock', '固定客', 24),
  ('love-rock', '福夢FUMON', 25),
  ('love-rock', '無妄合作社', 26),
  ('love-rock', '傷心欲絕', 27),
  ('love-rock', 'blu mush', 28),
  ('love-rock', '宇宙資料庫', 29),
  ('love-rock', '畫室', 30),
  ('love-rock', '秋波愛麗', 31),
  ('love-rock', '等阮返來', 32),
  ('love-rock', '咱不我予', 33),
  ('love-rock', '秋山', 34),
  ('love-rock', '微醺龐克', 35),
  ('love-rock', '伯爵先生', 36),
  ('love-rock', '蔗嗚子', 37),
  ('love-rock', 'Hbun 河紋', 38),
  ('love-rock', 'RIKI', 39),
  ('love-rock', '烈鷹', 40),
  ('love-rock', 'Snake 潘阿閔', 41),

  -- 赤聲躁動音樂祭 (hot-wave)
  ('hot-wave', '怕胖團 PAPUN BAND', 0),
  ('hot-wave', '血肉果汁機', 1),
  ('hot-wave', '芒果醬 Mango Jump', 2),
  ('hot-wave', '福夢 FUMON', 3),
  ('hot-wave', '溫室雜草', 4),
  ('hot-wave', 'INFERNAL CHAOS', 5),
  ('hot-wave', '庸俗救星 Vulgar Savior', 6),
  ('hot-wave', '紙鳶 Seizer', 7),
  ('hot-wave', 'Triple Deer', 8),
  ('hot-wave', '工口紳士 Ero Gent', 9),
  ('hot-wave', 'Xmoraz', 10),
  ('hot-wave', '碎紙花', 11),
  ('hot-wave', 'HOLOTROPICS', 12),
  ('hot-wave', '羊米人 YUMMY MAN', 13),
  ('hot-wave', 'Soul Sorry', 14),
  ('hot-wave', 'HYANG [KR]', 15),
  ('hot-wave', 'IRIS MONDO [JP]', 16),
  ('hot-wave', 'リュックと添い寝ごはん ryukku to soine gohan [JP]', 17),
  ('hot-wave', 'kiyu [JP]', 18),
  ('hot-wave', 'The Publish [TH]', 19),
  ('hot-wave', 'Aggressive Raisin Cat [SG]', 20),
  ('hot-wave', 'icyball 冰球樂團', 21),
  ('hot-wave', '溫蒂漫步 Wendy Wander', 22),
  ('hot-wave', 'wannasleep', 23),
  ('hot-wave', '公館青少年 GGteens', 24),
  ('hot-wave', '震樂堂', 25),
  ('hot-wave', '薄暮 EVENFALL', 26),
  ('hot-wave', '175R [JP]', 27),
  ('hot-wave', 'the engy [JP]', 28),
  ('hot-wave', 'pachae [JP]', 29),
  ('hot-wave', 'ギョウザマン GYOZAMAN [JP]', 30),
  ('hot-wave', 'FLAPSTAR [JP]', 31),
  ('hot-wave', 'THEΔRAREz', 32),
  ('hot-wave', '終焉Rebirth', 33),
  ('hot-wave', '국카스텐 Guckkasten [KR]', 34),
  ('hot-wave', '신인류 Shin In Ryu [KR]', 35),
  ('hot-wave', '해서웨이 hathaw9y [KR]', 36),
  ('hot-wave', '다다다 DADADA [KR]', 37),

  -- 春浪音樂節 (spring-wave)
  ('spring-wave', 'MEMI', 0),
  ('spring-wave', 'PeaceHotel 和平飯店', 1),
  ('spring-wave', '怕胖團 PAPUN BAND', 2),
  ('spring-wave', '康士坦的變化球 KST', 3),
  ('spring-wave', '傻子與白痴', 4),
  ('spring-wave', '溫室雜草', 5),
  ('spring-wave', '宋德鶴', 6),
  ('spring-wave', 'Lizi 栗子', 7),
  ('spring-wave', '慶記KTV-DJ Double K ft.小鐘', 8),
  ('spring-wave', '陳土豆', 9),
  ('spring-wave', '生祥樂隊', 10),
  ('spring-wave', '八三夭', 11),
  ('spring-wave', 'someshiit 山姆', 12),
  ('spring-wave', 'Multiverse Music', 13),
  ('spring-wave', '荒山茉莉', 14),
  ('spring-wave', 'SONNIE 桑尼', 15),
  ('spring-wave', '浪漫里', 16),
  ('spring-wave', '面白大丈夫 - 搞笑救星', 17),
  ('spring-wave', '愛希頌缽', 18),
  ('spring-wave', '看我笑話工作室', 19),
  ('spring-wave', '峸劇場 - BarART原創酒吧劇集', 20),
  ('spring-wave', 'EOM', 21),
  ('spring-wave', 'Omoinotake', 22),
  ('spring-wave', '告五人', 23),
  ('spring-wave', 'TRASH', 24),
  ('spring-wave', 'Karencici', 25),
  ('spring-wave', '芒果醬 Mango Jump', 26),
  ('spring-wave', '福夢 FUMON', 27),
  ('spring-wave', '百合花 Lilium', 28),
  ('spring-wave', '鳳小岳', 29),
  ('spring-wave', 'MONO NO AWARE', 30),
  ('spring-wave', '陳嫺靜', 31),
  ('spring-wave', '黃宇寒 Han', 32),
  ('spring-wave', '莉莉周她說 Lily Chou-Chou Lied', 33),
  ('spring-wave', '米莎Misa & 早川徹', 34),
  ('spring-wave', '粹垢 TRAEGO', 35),
  ('spring-wave', '核果人NUTS', 36),
  ('spring-wave', '宅邦戰隊', 37),
  ('spring-wave', 'TriForm', 38),

  -- 火球祭 (fireball)：陣容待公布，先以佔位藝人呈現。
  ('fireball', '待公布', 0)
)
insert into public.festival_artists (festival_id, artist_id, position)
select l.festival_id, a.id, l.position
from lineup l
join public.artists a on a.name = l.artist_name
on conflict (festival_id, artist_id) do update
  set position = excluded.position;
